"""PPTX skill public package (PR0 shim).

This package exposes the existing scripts/ modules through a stable namespace
while the V2 migration gradually moves authoritative implementations here.
"""
from __future__ import annotations

import sys
from pathlib import Path

_SKILL_ROOT = Path(__file__).resolve().parent.parent
_SCRIPTS_DIR = _SKILL_ROOT / "scripts"

if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

from ppt_edit import (  # noqa: E402
    edit_kicker,
    edit_text,
    edit_text_by_role,
    edit_title,
    recolor,
    swap_image,
    swap_theme,
)
from ppt_inspect import inspect_ppt  # noqa: E402
from ppt_pages import (  # noqa: E402
    delete_slide,
    duplicate_slide,
    insert_slide,
    move_slide,
    replace_layout,
)
from ppt_project import (  # noqa: E402
    create_backup,
    edit_section,
    load_project,
    regenerate,
    restore_backup,
)
from pptx_helper import (  # noqa: E402
    LAYOUT_REGISTRY,
    THEMES,
    Section,
    add_chart_slide,
    choose_layout,
    choose_theme,
)
from reference_ppt import (  # noqa: E402
    analyze_presentation,
    compose_from_reference,
    extract_template_profile,
    generate_from_reference,
)
from render_slides import render_slides  # noqa: E402
from template_engine import (  # noqa: E402
    generate_template_preview,
    generate_template_profile,
    list_templates,
    load_template_profile,
    register_template_profile,
    validate_template_profile,
)

from pptx_skill.api import (  # noqa: E402
    GenerationResult,
    auto_generate_ppt,
    auto_validate_ppt,
)
from pptx_skill.content_adapter import (  # noqa: E402
    LegacyContentAdapter,
    adapt_legacy_sections,
)
from pptx_skill.content_model import (  # noqa: E402
    CANVAS_PRESETS,
    BBox,
    CanvasSpec,
    ContentSpec,
    DeckPlanResult,
    ElementSpec,
    GeometrySpec,
    LayoutPlan,
    PlannedNode,
    SafeInsets,
    SlidePlanCandidate,
    SlidePlanResult,
    SlideSpec,
    StableIdGenerator,
    canvas_from_name,
    make_namespace,
)
from pptx_skill.deck_planner import (  # noqa: E402
    LayoutScoringConfig,
    plan_deck,
)
from pptx_skill.design_schema import (  # noqa: E402
    TEMPLATE_SCHEMA_VERSION,
    CompiledTemplateBundleV2,
    StyleIntent,
    bundle_to_dict,
    canvas_from_profile,
    resolve_all_tokens,
    resolve_token,
    validate_source_profile,
)
from pptx_skill.generation_pipeline import (  # noqa: E402
    LayoutPlanningError,
    plan_deck_layouts,
    run_generation_pipeline,
)
from pptx_skill.golden_renders import (  # noqa: E402
    ALL_ROLES,
    GEOMETRY_FAMILIES,
    GoldenIndex,
    GoldenPage,
    golden_coverage_report,
    load_golden_index,
    render_golden_set,
)
from pptx_skill.image_crop import (  # noqa: E402
    CropResult,
    crop_contain,
    crop_cover,
    crop_smart,
)
from pptx_skill.layout_engine import (  # noqa: E402
    CandidateBundle,
    Constraint,
    LayoutRecipe,
    SolvedGeometry,
    Term,
    builtin_recipes,
    plan_slide_candidates,
    recipe_from_dict,
    recipe_to_dict,
    solve_recipe,
    solved_geometry_to_layout_plan,
)
from pptx_skill.manifest import (  # noqa: E402
    ManifestError,
    ManifestV3,
    load_manifest,
    manifest_from_dict,
    manifest_to_dict,
    migrate_v2_to_v3,
    save_manifest_v3,
    set_current_content,
    set_current_plans,
    set_current_trace,
)
from pptx_skill.pagination import (  # noqa: E402
    IMAGE_GRID_LAYOUTS,
    ContentItem,
    FitResult,
    paginate_bullets,
    paginate_content_spec,
    paginate_image_grid,
    paginate_items,
    paginate_process,
    paginate_table,
    paginate_timeline,
)
from pptx_skill.pptx_renderer import (  # noqa: E402
    AdaptiveRendererError,
    PreviewRenderResult,
    RenderResult,
    RenderTraceEntry,
    render_layout_plan,
    render_layout_plans,
)
from pptx_skill.preview_renderer import render_preview  # noqa: E402
from pptx_skill.qa_dataset import (  # noqa: E402
    DATASET_CATEGORIES,
    DATASET_TOTAL_MIN,
    ISSUE_CLEAN,
    dataset_coverage_report,
    generate_annotation_dataset,
    load_annotation_dataset,
)
from pptx_skill.reference_adapter import (  # noqa: E402
    REFERENCE_MODES,
    ReferenceAdapterResult,
    ReferenceCanvasInfo,
    clone_mode_adapter,
    generate_from_reference_adapter,
    native_mode_adapter,
    reference_canvas,
)
from pptx_skill.render_qa import (  # noqa: E402
    RenderQAConfig,
    SlideDiff,
    compare_slide_to_baseline,
    evaluate_render_against_baseline,
)
from pptx_skill.repair_engine import (  # noqa: E402
    RepairAction,
    RepairActionKind,
    apply_repairs,
    merge_profile_overrides,
    propose_repairs,
)
from pptx_skill.semantic_qa import (  # noqa: E402
    DetectedIssue,
    IssueKind,
    IssueSeverity,
    SemanticQAEngine,
    SemanticQAReport,
    check_layout_plan,
    contrast_ratio,
)
from pptx_skill.template_compiler import (  # noqa: E402
    compile_from_intent,
    compile_source_profile,
    geometry_similarity,
    passes_diversity_gate,
    source_profile_from_intent,
)
from pptx_skill.template_v2_adapter import (  # noqa: E402
    migrate_and_compile_v1,
    migrate_profile_v1_to_v2,
    v2_bundle_to_legacy_fonts,
    v2_bundle_to_legacy_profile,
    v2_bundle_to_legacy_theme,
)
from pptx_skill.text_metrics import (  # noqa: E402
    LineMetrics,
    ParagraphStyle,
    TextMeasurer,
    TextMetrics,
    TextRun,
    fit_text_to_height,
    measure_runs,
    measure_text,
    resolve_font,
)
from pptx_skill.visual_qa import (  # noqa: E402
    CheckOutcome,
    PresentationQualityError,
    QACheckResult,
    QAIssue,
    QAReport,
    Severity,
)
from pptx_skill.visual_rebuild import (  # noqa: E402
    DEFAULT_SIMILARITY_BUDGET,
    REBUILD_RECIPE_PREFERENCE,
    ReferenceDiffRecord,
    SlideRebuildPlan,
    VisualRebuildResult,
    analyze_reference_deck,
    reference_rebuild_diff_report,
    visual_rebuild_adapter,
)
from pptx_skill.template_downloader import (  # noqa: E402
    download_template_pack,
    import_template,
    list_remote_packs,
    search_github_templates,
)
from pptx_skill.merge import (  # noqa: E402
    MergeResult,
    append_slides,
    extract_slides,
    insert_slides,
    merge_presentations,
)
from pptx_skill.transitions import (  # noqa: E402
    CUT,
    DISSOLVE,
    FADE,
    PUSH_DOWN,
    PUSH_LEFT,
    PUSH_RIGHT,
    PUSH_UP,
    RANDOM,
    SPLIT_HORIZONTAL_IN,
    SPLIT_HORIZONTAL_OUT,
    SPLIT_VERTICAL_IN,
    SPLIT_VERTICAL_OUT,
    COVER_LEFT,
    COVER_RIGHT,
    TRANSITION_TYPES,
    WIPE_DOWN,
    WIPE_LEFT,
    WIPE_RIGHT,
    WIPE_UP,
    apply_deck_transitions,
    apply_slide_transition,
)
from pptx_skill.animations import (  # noqa: E402
    ALL_ANIMATION_TYPES,
    ANIMATION_TYPES,
    APPEAR,
    ASCEND,
    BLINDS_IN,
    BLINDS_OUT,
    BOUNCE,
    BOUNCE_OUT,
    BOX_IN,
    BOX_OUT,
    BRUSH_ON_COLOR,
    BRUSH_ON_UNDERLINE,
    CHECKERBOARD_IN,
    CHECKERBOARD_OUT,
    COLOR_CHANGE,
    DARKEN,
    DESATURATE,
    DESCEND,
    DIAGONAL_IN,
    DIAGONAL_OUT,
    DISAPPEAR,
    EMPHASIS_TYPES,
    ENTRANCE_TYPES,
    EXIT_TYPES,
    FADE_IN,
    FADE_OUT,
    FILL_COLOR,
    FLOAT_DOWN,
    FLOAT_UP,
    FLY_IN,
    FLY_OUT,
    FONT_COLOR,
    GROW_SHRINK,
    GROW_TURN,
    LIGHTEN,
    MOTION_PATH,
    OBJECT_COLOR,
    PULSE,
    RANDOM_BARS_IN,
    RANDOM_BARS_OUT,
    SHRINK_TURN,
    SPIN,
    SPIN_IN,
    SPLIT_IN,
    SPLIT_OUT,
    STRETCH_IN,
    SWIVEL,
    SWIVEL_OUT,
    TEETER,
    TRANSPARENCY,
    WAVE,
    WHEEL_IN,
    WIPE_IN,
    WIPE_OUT,
    ZOOM,
    ZOOM_OUT,
    apply_animation,
    apply_emphasis_animation,
    apply_entrance_animation,
    apply_exit_animation,
    apply_motion_path,
    list_animations,
    remove_animations,
)
from pptx_skill.watermark import (  # noqa: E402
    add_image_watermark,
    add_text_watermark,
    list_watermarks,
    remove_watermark,
)
from pptx_skill.sections import (  # noqa: E402
    SectionInfo,
    add_section,
    collapse_section,
    list_sections,
    move_section,
    remove_section,
    rename_section,
)
from pptx_skill.slide_master import (  # noqa: E402
    LayoutInfo,
    MasterInfo,
    add_placeholder_to_layout,
    analyze_layout,
    clone_layout,
    delete_layout,
    get_layout_by_name,
    list_layouts,
    list_placeholders,
    list_slide_masters,
    remove_placeholder_from_layout,
    rename_layout,
    set_layout_background,
    set_master_background,
)
from pptx_skill.image_optimize import (  # noqa: E402
    CompressionLevel,
    compress_images,
    convert_image_format,
    get_image_stats,
    remove_unused_media,
)
from pptx_skill.comments import (  # noqa: E402
    add_comment,
    append_speaker_notes,
    delete_comment,
    export_speaker_notes,
    get_speaker_notes,
    list_comments,
    remove_speaker_notes,
    reply_to_comment,
    resolve_comment,
    set_speaker_notes,
)
from pptx_skill.diff import (  # noqa: E402
    Change,
    ChangeKind,
    PresentationDiff,
    SlideDiff,
    diff_presentations,
    diff_presentations_visual,
    diff_slides,
    diff_text,
    format_diff,
    has_changes,
)
from pptx_skill.export import (  # noqa: E402
    export_thumbnails,
    export_to_html,
    export_to_images,
    export_to_pdf,
    export_to_text,
)
from pptx_skill.html_import import (  # noqa: E402
    detect_html_slides,
    html_to_content_spec,
    import_from_html,
)
from pptx_skill.smartart import (  # noqa: E402
    detect_smartart,
    extract_smartart_text,
    list_smartart_layouts,
    populate_smartart_text,
    preserve_smartart,
    smartart_layout_info,
)
from pptx_skill.vba import (  # noqa: E402
    attach_macro_to_shape,
    detach_macro_from_shape,
    extract_vba_project,
    has_vba_project,
    inject_vba_project,
    list_macro_names,
    preserve_vba_project,
)
from pptx_skill.table_styles import (  # noqa: E402
    TABLE_STYLE_IDS,
    add_table_column,
    add_table_row,
    apply_table_style,
    merge_cells,
    set_cell_border,
    set_cell_fill,
    set_cell_margins,
    set_cell_vertical_alignment,
    set_table_banding,
    set_table_direction,
    unmerge_cells,
)
from pptx_skill.html_import import (  # noqa: E402
    detect_html_slides,
    html_to_content_spec,
    import_from_html,
)

__version__ = "3.0.0"


def __getattr__(name: str):
    """Lazy import for submodules to avoid circular imports on ``python -m``."""
    if name == "report_capabilities":
        from pptx_skill.capability import report_capabilities
        return report_capabilities
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "AdaptiveRendererError",
    "ALL_ROLES",
    "GEOMETRY_FAMILIES",
    "GoldenIndex",
    "GoldenPage",
    "DATASET_CATEGORIES",
    "DATASET_TOTAL_MIN",
    "ISSUE_CLEAN",
    # Data models
    "BBox",
    "CANVAS_PRESETS",
    "CanvasSpec",
    "CandidateBundle",
    "CheckOutcome",
    "CompiledTemplateBundleV2",
    "Constraint",
    "ContentItem",
    "ContentSpec",
    "CropResult",
    "DeckPlanResult",
    "DetectedIssue",
    "ElementSpec",
    "GenerationResult",
    "GeometrySpec",
    "IMAGE_GRID_LAYOUTS",
    "IssueKind",
    "IssueSeverity",
    "LAYOUT_REGISTRY",
    "LayoutPlanningError",
    "LayoutPlan",
    "LayoutRecipe",
    "LayoutScoringConfig",
    "LegacyContentAdapter",
    "LineMetrics",
    "ManifestError",
    "ManifestV3",
    "ParagraphStyle",
    "PlannedNode",
    "PreviewRenderResult",
    "PresentationQualityError",
    "QAReport",
    "QACheckResult",
    "QAIssue",
    "RenderQAConfig",
    "RenderResult",
    "RenderTraceEntry",
    "RepairAction",
    "RepairActionKind",
    "SafeInsets",
    "Section",
    "SemanticQAEngine",
    "SemanticQAReport",
    "Severity",
    "SlideDiff",
    "SlidePlanCandidate",
    "SlidePlanResult",
    "SlideSpec",
    "SolvedGeometry",
    "StableIdGenerator",
    "StyleIntent",
    "TEMPLATE_SCHEMA_VERSION",
    "THEMES",
    "Term",
    "TextMeasurer",
    "TextMetrics",
    "TextRun",
    "adapt_legacy_sections",
    "add_chart_slide",
    "analyze_presentation",
    "apply_repairs",
    "auto_generate_ppt",
    "auto_validate_ppt",
    "builtin_recipes",
    "canvas_from_name",
    "check_layout_plan",
    "choose_layout",
    "choose_theme",
    "clone_mode_adapter",
    "compare_slide_to_baseline",
    "compile_from_intent",
    "compile_source_profile",
    "compose_from_reference",
    "contrast_ratio",
    "create_backup",
    "crop_contain",
    "crop_cover",
    "crop_smart",
    "delete_slide",
    "duplicate_slide",
    "edit_kicker",
    "edit_section",
    "edit_text",
    "edit_text_by_role",
    "edit_title",
    "evaluate_render_against_baseline",
    "extract_template_profile",
    "fit_text_to_height",
    "FitResult",
    "generate_from_reference",
    "generate_from_reference_adapter",
    "generate_template_preview",
    "generate_template_profile",
    "geometry_similarity",
    "inspect_ppt",
    "insert_slide",
    "list_templates",
    "load_annotation_dataset",
    "load_golden_index",
    "load_manifest",
    "load_project",
    "load_template_profile",
    "make_namespace",
    "manifest_from_dict",
    "manifest_to_dict",
    "measure_runs",
    "measure_text",
    "merge_profile_overrides",
    "merge_presentations",
    "MergeResult",
    "migrate_and_compile_v1",
    "migrate_profile_v1_to_v2",
    "migrate_v2_to_v3",
    "move_slide",
    "native_mode_adapter",
    "bundle_to_dict",
    "canvas_from_profile",
    "paginate_bullets",
    "paginate_content_spec",
    "paginate_image_grid",
    "paginate_items",
    "paginate_process",
    "paginate_table",
    "paginate_timeline",
    "passes_diversity_gate",
    "plan_deck",
    "plan_deck_layouts",
    "plan_slide_candidates",
    "propose_repairs",
    "recolor",
    "recipe_from_dict",
    "recipe_to_dict",
    "regenerate",
    "register_template_profile",
    "REFERENCE_MODES",
    "ReferenceAdapterResult",
    "ReferenceCanvasInfo",
    "reference_canvas",
    "render_golden_set",
    "render_layout_plan",
    "render_layout_plans",
    "render_preview",
    "render_slides",
    "replace_layout",
    "report_capabilities",
    "resolve_all_tokens",
    "resolve_font",
    "resolve_token",
    "restore_backup",
    "run_generation_pipeline",
    "save_manifest_v3",
    "set_current_content",
    "set_current_plans",
    "set_current_trace",
    "solve_recipe",
    "solved_geometry_to_layout_plan",
    "swap_image",
    "swap_theme",
    "validate_template_profile",
    "source_profile_from_intent",
    "validate_source_profile",
    "v2_bundle_to_legacy_fonts",
    "v2_bundle_to_legacy_profile",
    "v2_bundle_to_legacy_theme",
    "visual_rebuild_adapter",
    "VisualRebuildResult",
    "analyze_reference_deck",
    "reference_rebuild_diff_report",
    "append_slides",
    "extract_slides",
    "insert_slides",
    "DEFAULT_SIMILARITY_BUDGET",
    "REBUILD_RECIPE_PREFERENCE",
    "ReferenceDiffRecord",
    "SlideRebuildPlan",
    "generate_annotation_dataset",
    "dataset_coverage_report",
    "golden_coverage_report",
    "download_template_pack",
    "import_template",
    "list_remote_packs",
    "search_github_templates",
    # Transitions
    "apply_deck_transitions",
    "apply_slide_transition",
    "CUT",
    "DISSOLVE",
    "FADE",
    "PUSH_DOWN",
    "PUSH_LEFT",
    "PUSH_RIGHT",
    "PUSH_UP",
    "RANDOM",
    "SPLIT_HORIZONTAL_IN",
    "SPLIT_HORIZONTAL_OUT",
    "SPLIT_VERTICAL_IN",
    "SPLIT_VERTICAL_OUT",
    "COVER_LEFT",
    "COVER_RIGHT",
    "TRANSITION_TYPES",
    "WIPE_DOWN",
    "WIPE_LEFT",
    "WIPE_RIGHT",
    "WIPE_UP",
    # Animations
    "ALL_ANIMATION_TYPES",
    "ANIMATION_TYPES",
    "APPEAR",
    "ASCEND",
    "BLINDS_IN",
    "BLINDS_OUT",
    "BOUNCE",
    "BOUNCE_OUT",
    "BOX_IN",
    "BOX_OUT",
    "BRUSH_ON_COLOR",
    "BRUSH_ON_UNDERLINE",
    "CHECKERBOARD_IN",
    "CHECKERBOARD_OUT",
    "COLOR_CHANGE",
    "DARKEN",
    "DESATURATE",
    "DESCEND",
    "DIAGONAL_IN",
    "DIAGONAL_OUT",
    "DISAPPEAR",
    "EMPHASIS_TYPES",
    "ENTRANCE_TYPES",
    "EXIT_TYPES",
    "FADE_IN",
    "FADE_OUT",
    "FILL_COLOR",
    "FLOAT_DOWN",
    "FLOAT_UP",
    "FLY_IN",
    "FLY_OUT",
    "FONT_COLOR",
    "GROW_SHRINK",
    "GROW_TURN",
    "LIGHTEN",
    "MOTION_PATH",
    "OBJECT_COLOR",
    "PULSE",
    "RANDOM_BARS_IN",
    "RANDOM_BARS_OUT",
    "SHRINK_TURN",
    "SPIN",
    "SPIN_IN",
    "SPLIT_IN",
    "SPLIT_OUT",
    "STRETCH_IN",
    "SWIVEL",
    "SWIVEL_OUT",
    "TEETER",
    "TRANSPARENCY",
    "WAVE",
    "WHEEL_IN",
    "WIPE_IN",
    "WIPE_OUT",
    "ZOOM",
    "ZOOM_OUT",
    "apply_animation",
    "apply_emphasis_animation",
    "apply_entrance_animation",
    "apply_exit_animation",
    "apply_motion_path",
    "list_animations",
    "remove_animations",
    # Watermark
    "add_image_watermark",
    "add_text_watermark",
    "list_watermarks",
    "remove_watermark",
    # Sections
    "SectionInfo",
    "add_section",
    "collapse_section",
    "list_sections",
    "move_section",
    "remove_section",
    "rename_section",
    # Slide Master
    "LayoutInfo",
    "MasterInfo",
    "add_placeholder_to_layout",
    "analyze_layout",
    "clone_layout",
    "delete_layout",
    "get_layout_by_name",
    "list_layouts",
    "list_placeholders",
    "list_slide_masters",
    "remove_placeholder_from_layout",
    "rename_layout",
    "set_layout_background",
    "set_master_background",
    # Image Optimize
    "CompressionLevel",
    "compress_images",
    "convert_image_format",
    "get_image_stats",
    "remove_unused_media",
    # Comments
    "add_comment",
    "append_speaker_notes",
    "delete_comment",
    "export_speaker_notes",
    "get_speaker_notes",
    "list_comments",
    "remove_speaker_notes",
    "reply_to_comment",
    "resolve_comment",
    "set_speaker_notes",
    # Diff
    "Change",
    "ChangeKind",
    "PresentationDiff",
    "SlideDiff",
    "diff_presentations",
    "diff_presentations_visual",
    "diff_slides",
    "diff_text",
    "format_diff",
    "has_changes",
    # Export
    "export_thumbnails",
    "export_to_html",
    "export_to_images",
    "export_to_pdf",
    "export_to_text",
    # HTML Import
    "detect_html_slides",
    "html_to_content_spec",
    "import_from_html",
    # SmartArt
    "detect_smartart",
    "extract_smartart_text",
    "list_smartart_layouts",
    "populate_smartart_text",
    "preserve_smartart",
    "smartart_layout_info",
    # VBA
    "attach_macro_to_shape",
    "detach_macro_from_shape",
    "extract_vba_project",
    "has_vba_project",
    "inject_vba_project",
    "list_macro_names",
    "preserve_vba_project",
    # Table Styles
    "TABLE_STYLE_IDS",
    "add_table_column",
    "add_table_row",
    "apply_table_style",
    "merge_cells",
    "set_cell_border",
    "set_cell_fill",
    "set_cell_margins",
    "set_cell_vertical_alignment",
    "set_table_banding",
    "set_table_direction",
    "unmerge_cells",
    # HTML Import
    "detect_html_slides",
    "html_to_content_spec",
    "import_from_html",
]
