"""PPTX skill public package (PR0 shim).

This package exposes the existing scripts/ modules through a stable namespace
while the V2 migration gradually moves authoritative implementations here.
"""
from __future__ import annotations

import sys
from pathlib import Path

_SKILL_ROOT = Path(__file__).resolve().parent.parent
_SCRIPTS_DIR = _SKILL_ROOT / "scripts"

if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

from ppt_edit import (  # noqa: E402
    edit_kicker,
    edit_text,
    edit_text_by_role,
    edit_title,
    recolor,
    swap_image,
    swap_theme,
)
from ppt_inspect import inspect_ppt  # noqa: E402
from ppt_pages import (  # noqa: E402
    delete_slide,
    duplicate_slide,
    insert_slide,
    move_slide,
    replace_layout,
)
from ppt_project import (  # noqa: E402
    create_backup,
    edit_section,
    load_project,
    regenerate,
    restore_backup,
)
from pptx_helper import (  # noqa: E402
    LAYOUT_REGISTRY,
    THEMES,
    Section,
    add_chart_slide,
    choose_layout,
    choose_theme,
)
from reference_ppt import (  # noqa: E402
    analyze_presentation,
    compose_from_reference,
    extract_template_profile,
    generate_from_reference,
)
from render_slides import render_slides  # noqa: E402
from template_engine import (  # noqa: E402
    generate_template_preview,
    generate_template_profile,
    list_templates,
    load_template_profile,
    register_template_profile,
    validate_template_profile,
)

from pptx_skill.api import (  # noqa: E402
    GenerationResult,
    auto_generate_ppt,
    auto_validate_ppt,
)
from pptx_skill.content_adapter import (  # noqa: E402
    LegacyContentAdapter,
    adapt_legacy_sections,
)
from pptx_skill.content_model import (  # noqa: E402
    CANVAS_PRESETS,
    BBox,
    CanvasSpec,
    ContentSpec,
    DeckPlanResult,
    ElementSpec,
    GeometrySpec,
    LayoutPlan,
    PlannedNode,
    SafeInsets,
    SlidePlanCandidate,
    SlidePlanResult,
    SlideSpec,
    StableIdGenerator,
    canvas_from_name,
    make_namespace,
)
from pptx_skill.deck_planner import (  # noqa: E402
    LayoutScoringConfig,
    plan_deck,
)
from pptx_skill.design_schema import (  # noqa: E402
    TEMPLATE_SCHEMA_VERSION,
    CompiledTemplateBundleV2,
    StyleIntent,
    bundle_to_dict,
    canvas_from_profile,
    resolve_all_tokens,
    resolve_token,
    validate_source_profile,
)
from pptx_skill.generation_pipeline import (  # noqa: E402
    LayoutPlanningError,
    plan_deck_layouts,
    run_generation_pipeline,
)
from pptx_skill.golden_renders import (  # noqa: E402
    ALL_ROLES,
    GEOMETRY_FAMILIES,
    GoldenIndex,
    GoldenPage,
    golden_coverage_report,
    load_golden_index,
    render_golden_set,
)
from pptx_skill.image_crop import (  # noqa: E402
    CropResult,
    crop_contain,
    crop_cover,
    crop_smart,
)
from pptx_skill.layout_engine import (  # noqa: E402
    CandidateBundle,
    Constraint,
    LayoutRecipe,
    SolvedGeometry,
    Term,
    builtin_recipes,
    plan_slide_candidates,
    recipe_from_dict,
    recipe_to_dict,
    solve_recipe,
    solved_geometry_to_layout_plan,
)
from pptx_skill.manifest import (  # noqa: E402
    ManifestError,
    ManifestV3,
    load_manifest,
    manifest_from_dict,
    manifest_to_dict,
    migrate_v2_to_v3,
    save_manifest_v3,
    set_current_content,
    set_current_plans,
    set_current_trace,
)
from pptx_skill.pagination import (  # noqa: E402
    IMAGE_GRID_LAYOUTS,
    ContentItem,
    FitResult,
    paginate_bullets,
    paginate_content_spec,
    paginate_image_grid,
    paginate_items,
    paginate_process,
    paginate_table,
    paginate_timeline,
)
from pptx_skill.pptx_renderer import (  # noqa: E402
    AdaptiveRendererError,
    PreviewRenderResult,
    RenderResult,
    RenderTraceEntry,
    render_layout_plan,
    render_layout_plans,
)
from pptx_skill.preview_renderer import render_preview  # noqa: E402
from pptx_skill.qa_dataset import (  # noqa: E402
    DATASET_CATEGORIES,
    DATASET_TOTAL_MIN,
    ISSUE_CLEAN,
    dataset_coverage_report,
    generate_annotation_dataset,
    load_annotation_dataset,
)
from pptx_skill.reference_adapter import (  # noqa: E402
    REFERENCE_MODES,
    ReferenceAdapterResult,
    ReferenceCanvasInfo,
    clone_mode_adapter,
    generate_from_reference_adapter,
    native_mode_adapter,
    reference_canvas,
)
from pptx_skill.render_qa import (  # noqa: E402
    RenderQAConfig,
    SlideDiff,
    compare_slide_to_baseline,
    evaluate_render_against_baseline,
)
from pptx_skill.repair_engine import (  # noqa: E402
    RepairAction,
    RepairActionKind,
    apply_repairs,
    merge_profile_overrides,
    propose_repairs,
)
from pptx_skill.semantic_qa import (  # noqa: E402
    DetectedIssue,
    IssueKind,
    IssueSeverity,
    SemanticQAEngine,
    SemanticQAReport,
    check_layout_plan,
    contrast_ratio,
)
from pptx_skill.template_compiler import (  # noqa: E402
    compile_from_intent,
    compile_source_profile,
    geometry_similarity,
    passes_diversity_gate,
    source_profile_from_intent,
)
from pptx_skill.template_v2_adapter import (  # noqa: E402
    migrate_and_compile_v1,
    migrate_profile_v1_to_v2,
    v2_bundle_to_legacy_fonts,
    v2_bundle_to_legacy_profile,
    v2_bundle_to_legacy_theme,
)
from pptx_skill.text_metrics import (  # noqa: E402
    LineMetrics,
    ParagraphStyle,
    TextMeasurer,
    TextMetrics,
    TextRun,
    fit_text_to_height,
    measure_runs,
    measure_text,
    resolve_font,
)
from pptx_skill.visual_qa import (  # noqa: E402
    CheckOutcome,
    PresentationQualityError,
    QACheckResult,
    QAIssue,
    QAReport,
    Severity,
)
from pptx_skill.visual_rebuild import (  # noqa: E402
    DEFAULT_SIMILARITY_BUDGET,
    REBUILD_RECIPE_PREFERENCE,
    ReferenceDiffRecord,
    SlideRebuildPlan,
    VisualRebuildResult,
    analyze_reference_deck,
    reference_rebuild_diff_report,
    visual_rebuild_adapter,
)
# NOTE: html_import symbols are imported once above (L424); the previous
# duplicate import block here was removed to avoid running the module twice.

__version__ = "5.1.0"

# --- New v4.0 modules ---
_LAZY_IMPORTS: dict[str, str] = {
    # accessibility (12)
    'AccessibilityIssue': 'accessibility:AccessibilityIssue',
    'AccessibilityReport': 'accessibility:AccessibilityReport',
    'accessibility_IssueKind': 'accessibility:IssueKind',  # alias of IssueKind
    'accessibility_IssueSeverity': 'accessibility:IssueSeverity',  # alias of IssueSeverity
    'add_title_to_slide': 'accessibility:add_title_to_slide',
    'audit_accessibility': 'accessibility:audit_accessibility',
    'check_accessibility_contrast': 'accessibility:check_contrast',  # alias of check_contrast
    'fix_accessibility': 'accessibility:fix_accessibility',
    'get_alt_text': 'accessibility:get_alt_text',
    'remove_alt_text': 'accessibility:remove_alt_text',
    'set_alt_text': 'accessibility:set_alt_text',
    'set_reading_order': 'accessibility:set_reading_order',
    # animations (63)
    'ALL_ANIMATION_TYPES': 'animations:ALL_ANIMATION_TYPES',
    'ANIMATION_TYPES': 'animations:ANIMATION_TYPES',
    'APPEAR': 'animations:APPEAR',
    'ASCEND': 'animations:ASCEND',
    'BLINDS_IN': 'animations:BLINDS_IN',
    'BLINDS_OUT': 'animations:BLINDS_OUT',
    'BOUNCE': 'animations:BOUNCE',
    'BOUNCE_OUT': 'animations:BOUNCE_OUT',
    'BOX_IN': 'animations:BOX_IN',
    'BOX_OUT': 'animations:BOX_OUT',
    'BRUSH_ON_COLOR': 'animations:BRUSH_ON_COLOR',
    'BRUSH_ON_UNDERLINE': 'animations:BRUSH_ON_UNDERLINE',
    'CHECKERBOARD_IN': 'animations:CHECKERBOARD_IN',
    'CHECKERBOARD_OUT': 'animations:CHECKERBOARD_OUT',
    'COLOR_CHANGE': 'animations:COLOR_CHANGE',
    'DARKEN': 'animations:DARKEN',
    'DESATURATE': 'animations:DESATURATE',
    'DESCEND': 'animations:DESCEND',
    'DIAGONAL_IN': 'animations:DIAGONAL_IN',
    'DIAGONAL_OUT': 'animations:DIAGONAL_OUT',
    'DISAPPEAR': 'animations:DISAPPEAR',
    'EMPHASIS_TYPES': 'animations:EMPHASIS_TYPES',
    'ENTRANCE_TYPES': 'animations:ENTRANCE_TYPES',
    'EXIT_TYPES': 'animations:EXIT_TYPES',
    'FADE_IN': 'animations:FADE_IN',
    'FADE_OUT': 'animations:FADE_OUT',
    'FILL_COLOR': 'animations:FILL_COLOR',
    'FLOAT_DOWN': 'animations:FLOAT_DOWN',
    'FLOAT_UP': 'animations:FLOAT_UP',
    'FLY_IN': 'animations:FLY_IN',
    'FLY_OUT': 'animations:FLY_OUT',
    'FONT_COLOR': 'animations:FONT_COLOR',
    'GROW_SHRINK': 'animations:GROW_SHRINK',
    'GROW_TURN': 'animations:GROW_TURN',
    'LIGHTEN': 'animations:LIGHTEN',
    'MOTION_PATH': 'animations:MOTION_PATH',
    'OBJECT_COLOR': 'animations:OBJECT_COLOR',
    'PULSE': 'animations:PULSE',
    'RANDOM_BARS_IN': 'animations:RANDOM_BARS_IN',
    'RANDOM_BARS_OUT': 'animations:RANDOM_BARS_OUT',
    'SHRINK_TURN': 'animations:SHRINK_TURN',
    'SPIN': 'animations:SPIN',
    'SPIN_IN': 'animations:SPIN_IN',
    'SPLIT_IN': 'animations:SPLIT_IN',
    'SPLIT_OUT': 'animations:SPLIT_OUT',
    'STRETCH_IN': 'animations:STRETCH_IN',
    'SWIVEL': 'animations:SWIVEL',
    'SWIVEL_OUT': 'animations:SWIVEL_OUT',
    'TEETER': 'animations:TEETER',
    'TRANSPARENCY': 'animations:TRANSPARENCY',
    'WAVE': 'animations:WAVE',
    'WHEEL_IN': 'animations:WHEEL_IN',
    'WIPE_IN': 'animations:WIPE_IN',
    'WIPE_OUT': 'animations:WIPE_OUT',
    'ZOOM': 'animations:ZOOM',
    'ZOOM_OUT': 'animations:ZOOM_OUT',
    'apply_animation': 'animations:apply_animation',
    'apply_emphasis_animation': 'animations:apply_emphasis_animation',
    'apply_entrance_animation': 'animations:apply_entrance_animation',
    'apply_exit_animation': 'animations:apply_exit_animation',
    'apply_motion_path': 'animations:apply_motion_path',
    'list_animations': 'animations:list_animations',
    'remove_animations': 'animations:remove_animations',
    # batch (10)
    'BatchResult': 'batch:BatchResult',
    'BatchStats': 'batch:BatchStats',
    'batch_apply': 'batch:batch_apply',
    'batch_convert': 'batch:batch_convert',
    'batch_export_images': 'batch:batch_export_images',
    'batch_inspect': 'batch:batch_inspect',
    'batch_merge': 'batch:batch_merge',
    'batch_recolor': 'batch:batch_recolor',
    'batch_stats': 'batch:batch_stats',
    'batch_watermark': 'batch:batch_watermark',
    # chart_edit (19)
    'ChartInfo': 'chart_edit:ChartInfo',
    'SeriesInfo': 'chart_edit:SeriesInfo',
    'add_chart_series': 'chart_edit:add_chart_series',
    'edit_chart_data': 'chart_edit:edit_chart_data',
    'export_chart_data': 'chart_edit:export_chart_data',
    'get_chart_info': 'chart_edit:get_chart_info',
    'import_chart_data': 'chart_edit:import_chart_data',
    'list_charts': 'chart_edit:list_charts',
    'remove_chart_series': 'chart_edit:remove_chart_series',
    'rename_chart_series': 'chart_edit:rename_chart_series',
    'set_axis_number_format': 'chart_edit:set_axis_number_format',
    'set_axis_range': 'chart_edit:set_axis_range',
    'set_axis_title': 'chart_edit:set_axis_title',
    'set_chart_colors': 'chart_edit:set_chart_colors',
    'set_chart_style': 'chart_edit:set_chart_style',
    'set_chart_type': 'chart_edit:set_chart_type',
    'set_data_labels': 'chart_edit:set_data_labels',
    'set_legend': 'chart_edit:set_legend',
    'toggle_gridlines': 'chart_edit:toggle_gridlines',
    # color (28)
    'ColorInfo': 'color:ColorInfo',
    'GradientInfo': 'color:GradientInfo',
    'GradientStop': 'color:GradientStop',
    'analogous_colors': 'color:analogous_colors',
    'apply_gradient': 'color:apply_gradient',
    'blend_colors': 'color:blend_colors',
    'cmyk_to_rgb': 'color:cmyk_to_rgb',
    'complementary_colors': 'color:complementary_colors',
    'contrast_color': 'color:contrast_color',
    'darken': 'color:darken',
    'extract_palette': 'color:extract_palette',
    'hex_to_rgb': 'color:hex_to_rgb',
    'hsl_to_rgb': 'color:hsl_to_rgb',
    'hsv_to_rgb': 'color:hsv_to_rgb',
    'lighten': 'color:lighten',
    'list_gradients': 'color:list_gradients',
    'monochromatic_colors': 'color:monochromatic_colors',
    'recolor_presentation': 'color:recolor_presentation',
    'remove_gradient': 'color:remove_gradient',
    'resolve_theme_color': 'color:resolve_theme_color',
    'rgb_to_cmyk': 'color:rgb_to_cmyk',
    'rgb_to_hex': 'color:rgb_to_hex',
    'rgb_to_hsl': 'color:rgb_to_hsl',
    'rgb_to_hsv': 'color:rgb_to_hsv',
    'split_complementary_colors': 'color:split_complementary_colors',
    'swap_colors': 'color:swap_colors',
    'tetradic_colors': 'color:tetradic_colors',
    'triadic_colors': 'color:triadic_colors',
    # comments (10)
    'add_comment': 'comments:add_comment',
    'append_speaker_notes': 'comments:append_speaker_notes',
    'delete_comment': 'comments:delete_comment',
    'export_speaker_notes': 'comments:export_speaker_notes',
    'get_speaker_notes': 'comments:get_speaker_notes',
    'list_comments': 'comments:list_comments',
    'remove_speaker_notes': 'comments:remove_speaker_notes',
    'reply_to_comment': 'comments:reply_to_comment',
    'resolve_comment': 'comments:resolve_comment',
    'set_speaker_notes': 'comments:set_speaker_notes',
    # connectors (29)
    'ARROW_DIAMOND': 'connectors:ARROW_DIAMOND',
    'ARROW_NONE': 'connectors:ARROW_NONE',
    'ARROW_OPEN': 'connectors:ARROW_OPEN',
    'ARROW_OVAL': 'connectors:ARROW_OVAL',
    'ARROW_STEALTH': 'connectors:ARROW_STEALTH',
    'ARROW_TRIANGLE': 'connectors:ARROW_TRIANGLE',
    'ConnectorInfo': 'connectors:ConnectorInfo',
    'DASH_DASH': 'connectors:DASH_DASH',
    'DASH_DASH_DOT': 'connectors:DASH_DASH_DOT',
    'DASH_DOT': 'connectors:DASH_DOT',
    'DASH_LG_DASH': 'connectors:DASH_LG_DASH',
    'DASH_LG_DASH_DOT': 'connectors:DASH_LG_DASH_DOT',
    'DASH_LG_DASH_DOT_DOT': 'connectors:DASH_LG_DASH_DOT_DOT',
    'DASH_SOLID': 'connectors:DASH_SOLID',
    'DASH_SYS_DASH': 'connectors:DASH_SYS_DASH',
    'DASH_SYS_DASH_DOT': 'connectors:DASH_SYS_DASH_DOT',
    'DASH_SYS_DOT': 'connectors:DASH_SYS_DOT',
    'LineInfo': 'connectors:LineInfo',
    'add_connector': 'connectors:add_connector',
    'add_curve': 'connectors:add_curve',
    'add_curved_connector': 'connectors:add_curved_connector',
    'add_elbow_connector': 'connectors:add_elbow_connector',
    'add_freeform': 'connectors:add_freeform',
    'add_line': 'connectors:add_line',
    'delete_connector': 'connectors:delete_connector',
    'list_connectors': 'connectors:list_connectors',
    'reroute_connector': 'connectors:reroute_connector',
    'set_arrow_style': 'connectors:set_arrow_style',
    'set_line_style': 'connectors:set_line_style',
    # diff (10)
    'Change': 'diff:Change',
    'ChangeKind': 'diff:ChangeKind',
    'PresentationDiff': 'diff:PresentationDiff',
    'diff_SlideDiff': 'diff:SlideDiff',  # alias of SlideDiff
    'diff_presentations': 'diff:diff_presentations',
    'diff_presentations_visual': 'diff:diff_presentations_visual',
    'diff_slides': 'diff:diff_slides',
    'diff_text': 'diff:diff_text',
    'format_diff': 'diff:format_diff',
    'has_changes': 'diff:has_changes',
    # effects (24)
    'BevelPreset': 'effects:BevelPreset',
    'EFFECT_PRESETS': 'effects:EFFECT_PRESETS',
    'EffectInfo': 'effects:EffectInfo',
    'LightingPreset': 'effects:LightingPreset',
    'MaterialPreset': 'effects:MaterialPreset',
    'apply_3d_format': 'effects:apply_3d_format',
    'apply_effect_preset': 'effects:apply_effect_preset',
    'apply_glow': 'effects:apply_glow',
    'apply_inner_shadow': 'effects:apply_inner_shadow',
    'apply_perspective_shadow': 'effects:apply_perspective_shadow',
    'apply_reflection': 'effects:apply_reflection',
    'apply_shadow': 'effects:apply_shadow',
    'apply_soft_edges': 'effects:apply_soft_edges',
    'effects_cm_to_emu': 'effects:cm_to_emu',  # alias of cm_to_emu
    'effects_inch_to_emu': 'effects:inch_to_emu',  # alias of inch_to_emu
    'effects_pt_to_emu': 'effects:pt_to_emu',  # alias of pt_to_emu
    'list_effects': 'effects:list_effects',
    'remove_3d_format': 'effects:remove_3d_format',
    'remove_effect': 'effects:remove_effect',
    'remove_effects': 'effects:remove_effects',
    'remove_glow': 'effects:remove_glow',
    'remove_reflection': 'effects:remove_reflection',
    'remove_shadow': 'effects:remove_shadow',
    'remove_soft_edges': 'effects:remove_soft_edges',
    # equations (22)
    'OmmlBuilder': 'equations:OmmlBuilder',
    'add_display_equation': 'equations:add_display_equation',
    'add_equation': 'equations:add_equation',
    'add_equation_accent': 'equations:add_accent',  # alias of add_accent
    'add_equation_bar': 'equations:add_bar',  # alias of add_bar
    'add_equation_border_box': 'equations:add_equation_box',  # alias of add_equation_box
    'add_equation_delimiter': 'equations:add_delimiter',  # alias of add_delimiter
    'add_equation_fraction': 'equations:add_fraction',  # alias of add_fraction
    'add_equation_function': 'equations:add_function',  # alias of add_function
    'add_equation_group_character': 'equations:add_group_character',  # alias of add_group_character
    'add_equation_limit_lower': 'equations:add_limit_lower',  # alias of add_limit_lower
    'add_equation_limit_upper': 'equations:add_limit_upper',  # alias of add_limit_upper
    'add_equation_matrix': 'equations:add_matrix',  # alias of add_matrix
    'add_equation_nary': 'equations:add_nary',  # alias of add_nary
    'add_equation_radical': 'equations:add_radical',  # alias of add_radical
    'add_equation_sub_superscript': 'equations:add_sub_superscript',  # alias of add_sub_superscript
    'add_equation_subscript': 'equations:add_subscript',  # alias of add_subscript
    'add_equation_superscript': 'equations:add_superscript',  # alias of add_superscript
    'add_equation_text_run': 'equations:add_text_run',  # alias of add_text_run
    'latex_to_omml': 'equations:latex_to_omml',
    'list_equations': 'equations:list_equations',
    'remove_equation': 'equations:remove_equation',
    # export (5)
    'export_thumbnails': 'export:export_thumbnails',
    'export_to_html': 'export:export_to_html',
    'export_to_images': 'export:export_to_images',
    'export_to_pdf': 'export:export_to_pdf',
    'export_to_text': 'export:export_to_text',
    # groups (8)
    'GroupInfo': 'groups:GroupInfo',
    'add_to_group': 'groups:add_to_group',
    'group_shapes': 'groups:group_shapes',
    'list_group_children': 'groups:list_group_children',
    'list_groups': 'groups:list_groups',
    'move_in_group': 'groups:move_in_group',
    'remove_from_group': 'groups:remove_from_group',
    'ungroup_shapes': 'groups:ungroup_shapes',
    # html_import (3)
    'detect_html_slides': 'html_import:detect_html_slides',
    'html_to_content_spec': 'html_import:html_to_content_spec',
    'import_from_html': 'html_import:import_from_html',
    # image_optimize (5)
    'CompressionLevel': 'image_optimize:CompressionLevel',
    'compress_images': 'image_optimize:compress_images',
    'convert_image_format': 'image_optimize:convert_image_format',
    'get_image_stats': 'image_optimize:get_image_stats',
    'remove_unused_media': 'image_optimize:remove_unused_media',
    # layout_sync (16)
    'LayoutTemplate': 'layout_sync:LayoutTemplate',
    'align_shapes': 'layout_sync:align_shapes',
    'apply_layout_template': 'layout_sync:apply_layout_template',
    'bring_to_front': 'layout_sync:bring_to_front',
    'center_on_slide': 'layout_sync:center_on_slide',
    'copy_layout': 'layout_sync:copy_layout',
    'create_layout_template': 'layout_sync:create_layout_template',
    'distribute_shapes': 'layout_sync:distribute_shapes',
    'list_layout_templates': 'layout_sync:list_layout_templates',
    'match_position': 'layout_sync:match_position',
    'match_size': 'layout_sync:match_size',
    'move_down': 'layout_sync:move_down',
    'move_up': 'layout_sync:move_up',
    'send_to_back': 'layout_sync:send_to_back',
    'set_z_order': 'layout_sync:set_z_order',
    'snap_to_grid': 'layout_sync:snap_to_grid',
    # markdown_export (4)
    'MarkdownOptions': 'markdown_export:MarkdownOptions',
    'export_to_markdown': 'markdown_export:export_to_markdown',
    'extract_markdown_content': 'markdown_export:extract_markdown_content',
    'slide_to_markdown': 'markdown_export:slide_to_markdown',
    # merge (5)
    'MergeResult': 'merge:MergeResult',
    'append_slides': 'merge:append_slides',
    'extract_slides': 'merge:extract_slides',
    'insert_slides': 'merge:insert_slides',
    'merge_presentations': 'merge:merge_presentations',
    # metadata (12)
    'CustomProperty': 'metadata:CustomProperty',
    'DocumentMetadata': 'metadata:DocumentMetadata',
    'FontInfo': 'metadata:FontInfo',
    'delete_custom_property': 'metadata:delete_custom_property',
    'embed_font': 'metadata:embed_font',
    'get_custom_property': 'metadata:get_custom_property',
    'get_metadata': 'metadata:get_metadata',
    'list_custom_properties': 'metadata:list_custom_properties',
    'list_embedded_fonts': 'metadata:list_embedded_fonts',
    'remove_embedded_font': 'metadata:remove_embedded_font',
    'set_custom_property': 'metadata:set_custom_property',
    'set_metadata': 'metadata:set_metadata',
    # morph (6)
    'MorphInfo': 'morph:MorphInfo',
    'has_morph_transition': 'morph:has_morph_transition',
    'list_morph_transitions': 'morph:list_morph_transitions',
    'remove_morph_transition': 'morph:remove_morph_transition',
    'set_morph_options': 'morph:set_morph_options',
    'set_morph_transition': 'morph:set_morph_transition',
    # multimedia (10)
    'AudioInfo': 'multimedia:AudioInfo',
    'VideoInfo': 'multimedia:VideoInfo',
    'add_audio': 'multimedia:add_audio',
    'add_video': 'multimedia:add_video',
    'extract_audio': 'multimedia:extract_audio',
    'extract_video': 'multimedia:extract_video',
    'list_media': 'multimedia:list_media',
    'remove_media': 'multimedia:remove_media',
    'set_audio_playback': 'multimedia:set_audio_playback',
    'set_video_playback': 'multimedia:set_video_playback',
    # ocr (8)
    'OcrEngine': 'ocr:OcrEngine',
    'OcrResult': 'ocr:OcrResult',
    'auto_caption_presentation': 'ocr:auto_caption_presentation',
    'auto_caption_slide': 'ocr:auto_caption_slide',
    'list_available_engines': 'ocr:list_available_engines',
    'ocr_image': 'ocr:ocr_image',
    'ocr_presentation': 'ocr:ocr_presentation',
    'ocr_slide': 'ocr:ocr_slide',
    # protection (10)
    'ProtectionInfo': 'protection:ProtectionInfo',
    'apply_write_protection': 'protection:apply_write_protection',
    'decrypt_pptx': 'protection:decrypt_pptx',
    'encrypt_pptx': 'protection:encrypt_pptx',
    'get_protection_info': 'protection:get_protection_info',
    'is_encrypted': 'protection:is_encrypted',
    'is_marked_final': 'protection:is_marked_final',
    'mark_as_final': 'protection:mark_as_final',
    'remove_write_protection': 'protection:remove_write_protection',
    'unmark_as_final': 'protection:unmark_as_final',
    # sections (7)
    'SectionInfo': 'sections:SectionInfo',
    'add_section': 'sections:add_section',
    'collapse_section': 'sections:collapse_section',
    'list_sections': 'sections:list_sections',
    'move_section': 'sections:move_section',
    'remove_section': 'sections:remove_section',
    'rename_section': 'sections:rename_section',
    # slide_master (14)
    'LayoutInfo': 'slide_master:LayoutInfo',
    'MasterInfo': 'slide_master:MasterInfo',
    'add_placeholder_to_layout': 'slide_master:add_placeholder_to_layout',
    'analyze_layout': 'slide_master:analyze_layout',
    'clone_layout': 'slide_master:clone_layout',
    'delete_layout': 'slide_master:delete_layout',
    'get_layout_by_name': 'slide_master:get_layout_by_name',
    'list_layouts': 'slide_master:list_layouts',
    'list_placeholders': 'slide_master:list_placeholders',
    'list_slide_masters': 'slide_master:list_slide_masters',
    'remove_placeholder_from_layout': 'slide_master:remove_placeholder_from_layout',
    'rename_layout': 'slide_master:rename_layout',
    'set_layout_background': 'slide_master:set_layout_background',
    'set_master_background': 'slide_master:set_master_background',
    # smartart (6)
    'detect_smartart': 'smartart:detect_smartart',
    'extract_smartart_text': 'smartart:extract_smartart_text',
    'list_smartart_layouts': 'smartart:list_smartart_layouts',
    'populate_smartart_text': 'smartart:populate_smartart_text',
    'preserve_smartart': 'smartart:preserve_smartart',
    'smartart_layout_info': 'smartart:smartart_layout_info',
    # svg_export (3)
    'export_slide_to_svg': 'svg_export:export_slide_to_svg',
    'export_to_svg': 'svg_export:export_to_svg',
    'shape_to_svg': 'svg_export:shape_to_svg',
    # svg_import (5)
    'PathData': 'svg_import:PathData',
    'import_svg': 'svg_import:import_svg',
    'import_svg_as_image': 'svg_import:import_svg_as_image',
    'list_svg_shapes': 'svg_import:list_svg_shapes',
    'svg_to_drawingml': 'svg_import:svg_to_drawingml',
    # table_styles (12)
    'TABLE_STYLE_IDS': 'table_styles:TABLE_STYLE_IDS',
    'add_table_column': 'table_styles:add_table_column',
    'add_table_row': 'table_styles:add_table_row',
    'apply_table_style': 'table_styles:apply_table_style',
    'merge_cells': 'table_styles:merge_cells',
    'set_cell_border': 'table_styles:set_cell_border',
    'set_cell_fill': 'table_styles:set_cell_fill',
    'set_cell_margins': 'table_styles:set_cell_margins',
    'set_cell_vertical_alignment': 'table_styles:set_cell_vertical_alignment',
    'set_table_banding': 'table_styles:set_table_banding',
    'set_table_direction': 'table_styles:set_table_direction',
    'unmerge_cells': 'table_styles:unmerge_cells',
    # template_downloader (4)
    'download_template_pack': 'template_downloader:download_template_pack',
    'import_template': 'template_downloader:import_template',
    'list_remote_packs': 'template_downloader:list_remote_packs',
    'search_github_templates': 'template_downloader:search_github_templates',
    # transitions (21)
    'COVER_LEFT': 'transitions:COVER_LEFT',
    'COVER_RIGHT': 'transitions:COVER_RIGHT',
    'CUT': 'transitions:CUT',
    'DISSOLVE': 'transitions:DISSOLVE',
    'FADE': 'transitions:FADE',
    'PUSH_DOWN': 'transitions:PUSH_DOWN',
    'PUSH_LEFT': 'transitions:PUSH_LEFT',
    'PUSH_RIGHT': 'transitions:PUSH_RIGHT',
    'PUSH_UP': 'transitions:PUSH_UP',
    'RANDOM': 'transitions:RANDOM',
    'SPLIT_HORIZONTAL_IN': 'transitions:SPLIT_HORIZONTAL_IN',
    'SPLIT_HORIZONTAL_OUT': 'transitions:SPLIT_HORIZONTAL_OUT',
    'SPLIT_VERTICAL_IN': 'transitions:SPLIT_VERTICAL_IN',
    'SPLIT_VERTICAL_OUT': 'transitions:SPLIT_VERTICAL_OUT',
    'TRANSITION_TYPES': 'transitions:TRANSITION_TYPES',
    'WIPE_DOWN': 'transitions:WIPE_DOWN',
    'WIPE_LEFT': 'transitions:WIPE_LEFT',
    'WIPE_RIGHT': 'transitions:WIPE_RIGHT',
    'WIPE_UP': 'transitions:WIPE_UP',
    'apply_deck_transitions': 'transitions:apply_deck_transitions',
    'apply_slide_transition': 'transitions:apply_slide_transition',
    # transitions_ext (10)
    'ADVANCED_TRANSITIONS': 'transitions_ext:ADVANCED_TRANSITIONS',
    'AdvancedTransitionInfo': 'transitions_ext:AdvancedTransitionInfo',
    'has_advanced_transition': 'transitions_ext:has_advanced_transition',
    'list_advanced_transitions': 'transitions_ext:list_advanced_transitions',
    'remove_advanced_transition': 'transitions_ext:remove_advanced_transition',
    'set_advanced_transition': 'transitions_ext:set_advanced_transition',
    'set_flip_transition': 'transitions_ext:set_flip_transition',
    'set_pan_transition': 'transitions_ext:set_pan_transition',
    'set_ripple_transition': 'transitions_ext:set_ripple_transition',
    'set_wheel_transition': 'transitions_ext:set_wheel_transition',
    # vba (7)
    'attach_macro_to_shape': 'vba:attach_macro_to_shape',
    'detach_macro_from_shape': 'vba:detach_macro_from_shape',
    'extract_vba_project': 'vba:extract_vba_project',
    'has_vba_project': 'vba:has_vba_project',
    'inject_vba_project': 'vba:inject_vba_project',
    'list_macro_names': 'vba:list_macro_names',
    'preserve_vba_project': 'vba:preserve_vba_project',
    # video (6)
    'VideoExportOptions': 'video:VideoExportOptions',
    'check_ffmpeg': 'video:check_ffmpeg',
    'export_to_gif': 'video:export_to_gif',
    'export_to_video': 'video:export_to_video',
    'extract_audio_track': 'video:extract_audio_track',
    'video_VideoInfo': 'video:VideoInfo',  # alias of VideoInfo
    # watermark (4)
    'add_image_watermark': 'watermark:add_image_watermark',
    'add_text_watermark': 'watermark:add_text_watermark',
    'list_watermarks': 'watermark:list_watermarks',
    'remove_watermark': 'watermark:remove_watermark',
    # zoom (6)
    'ZoomInfo': 'zoom:ZoomInfo',
    'add_section_zoom': 'zoom:add_section_zoom',
    'add_slide_zoom': 'zoom:add_slide_zoom',
    'add_summary_zoom': 'zoom:add_summary_zoom',
    'list_zooms': 'zoom:list_zooms',
    'remove_zoom': 'zoom:remove_zoom',
}

def __getattr__(name: str):
    """Lazy-load extension capability symbols on first access (PEP 562).

    Core modules and the legacy ``scripts/`` entry points stay eagerly imported
    above; ~35 extension modules (animations, smartart, svg_import, ...) are
    loaded here on demand so ``import pptx_skill`` no longer parses ~9000 lines
    of OOXML helpers up front. Both ``from pptx_skill import X`` and
    ``from pptx_skill.<module> import X`` keep working.

    The map value is ``"<module>:<original_name>"``; plain imports have the two
    equal, aliases (e.g. ``SlideDiff as diff_SlideDiff``) record the module's
    real symbol name so ``getattr`` resolves correctly.
    """
    spec = _LAZY_IMPORTS.get(name)
    if spec is not None:
        module_name, _, attr = spec.partition(":")
        import importlib
        module = importlib.import_module(f"pptx_skill.{module_name}")
        value = getattr(module, attr)
        globals()[name] = value  # cache so subsequent lookups skip the dispatch
        return value
    if name == "report_capabilities":
        from pptx_skill.capability import report_capabilities
        return report_capabilities
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")



__all__ = [
    "AdaptiveRendererError",
    "ALL_ROLES",
    "GEOMETRY_FAMILIES",
    "GoldenIndex",
    "GoldenPage",
    "DATASET_CATEGORIES",
    "DATASET_TOTAL_MIN",
    "ISSUE_CLEAN",
    # Data models
    "BBox",
    "CANVAS_PRESETS",
    "CanvasSpec",
    "CandidateBundle",
    "CheckOutcome",
    "CompiledTemplateBundleV2",
    "Constraint",
    "ContentItem",
    "ContentSpec",
    "CropResult",
    "DeckPlanResult",
    "DetectedIssue",
    "ElementSpec",
    "GenerationResult",
    "GeometrySpec",
    "IMAGE_GRID_LAYOUTS",
    "IssueKind",
    "IssueSeverity",
    "LAYOUT_REGISTRY",
    "LayoutPlanningError",
    "LayoutPlan",
    "LayoutRecipe",
    "LayoutScoringConfig",
    "LegacyContentAdapter",
    "LineMetrics",
    "ManifestError",
    "ManifestV3",
    "ParagraphStyle",
    "PlannedNode",
    "PreviewRenderResult",
    "PresentationQualityError",
    "QAReport",
    "QACheckResult",
    "QAIssue",
    "RenderQAConfig",
    "RenderResult",
    "RenderTraceEntry",
    "RepairAction",
    "RepairActionKind",
    "SafeInsets",
    "Section",
    "SemanticQAEngine",
    "SemanticQAReport",
    "Severity",
    "SlideDiff",
    "SlidePlanCandidate",
    "SlidePlanResult",
    "SlideSpec",
    "SolvedGeometry",
    "StableIdGenerator",
    "StyleIntent",
    "TEMPLATE_SCHEMA_VERSION",
    "THEMES",
    "Term",
    "TextMeasurer",
    "TextMetrics",
    "TextRun",
    "adapt_legacy_sections",
    "add_chart_slide",
    "analyze_presentation",
    "apply_repairs",
    "auto_generate_ppt",
    "auto_validate_ppt",
    "builtin_recipes",
    "canvas_from_name",
    "check_layout_plan",
    "choose_layout",
    "choose_theme",
    "clone_mode_adapter",
    "compare_slide_to_baseline",
    "compile_from_intent",
    "compile_source_profile",
    "compose_from_reference",
    "contrast_ratio",
    "create_backup",
    "crop_contain",
    "crop_cover",
    "crop_smart",
    "delete_slide",
    "duplicate_slide",
    "edit_kicker",
    "edit_section",
    "edit_text",
    "edit_text_by_role",
    "edit_title",
    "evaluate_render_against_baseline",
    "extract_template_profile",
    "fit_text_to_height",
    "FitResult",
    "generate_from_reference",
    "generate_from_reference_adapter",
    "generate_template_preview",
    "generate_template_profile",
    "geometry_similarity",
    "inspect_ppt",
    "insert_slide",
    "list_templates",
    "load_annotation_dataset",
    "load_golden_index",
    "load_manifest",
    "load_project",
    "load_template_profile",
    "make_namespace",
    "manifest_from_dict",
    "manifest_to_dict",
    "measure_runs",
    "measure_text",
    "merge_profile_overrides",
    "merge_presentations",
    "MergeResult",
    "migrate_and_compile_v1",
    "migrate_profile_v1_to_v2",
    "migrate_v2_to_v3",
    "move_slide",
    "native_mode_adapter",
    "bundle_to_dict",
    "canvas_from_profile",
    "paginate_bullets",
    "paginate_content_spec",
    "paginate_image_grid",
    "paginate_items",
    "paginate_process",
    "paginate_table",
    "paginate_timeline",
    "passes_diversity_gate",
    "plan_deck",
    "plan_deck_layouts",
    "plan_slide_candidates",
    "propose_repairs",
    "recolor",
    "recipe_from_dict",
    "recipe_to_dict",
    "regenerate",
    "register_template_profile",
    "REFERENCE_MODES",
    "ReferenceAdapterResult",
    "ReferenceCanvasInfo",
    "reference_canvas",
    "render_golden_set",
    "render_layout_plan",
    "render_layout_plans",
    "render_preview",
    "render_slides",
    "replace_layout",
    "report_capabilities",
    "resolve_all_tokens",
    "resolve_font",
    "resolve_token",
    "restore_backup",
    "run_generation_pipeline",
    "save_manifest_v3",
    "set_current_content",
    "set_current_plans",
    "set_current_trace",
    "solve_recipe",
    "solved_geometry_to_layout_plan",
    "swap_image",
    "swap_theme",
    "validate_template_profile",
    "source_profile_from_intent",
    "validate_source_profile",
    "v2_bundle_to_legacy_fonts",
    "v2_bundle_to_legacy_profile",
    "v2_bundle_to_legacy_theme",
    "visual_rebuild_adapter",
    "VisualRebuildResult",
    "analyze_reference_deck",
    "reference_rebuild_diff_report",
    "append_slides",
    "extract_slides",
    "insert_slides",
    "DEFAULT_SIMILARITY_BUDGET",
    "REBUILD_RECIPE_PREFERENCE",
    "ReferenceDiffRecord",
    "SlideRebuildPlan",
    "generate_annotation_dataset",
    "dataset_coverage_report",
    "golden_coverage_report",
    "download_template_pack",
    "import_template",
    "list_remote_packs",
    "search_github_templates",
    # Transitions
    "apply_deck_transitions",
    "apply_slide_transition",
    "CUT",
    "DISSOLVE",
    "FADE",
    "PUSH_DOWN",
    "PUSH_LEFT",
    "PUSH_RIGHT",
    "PUSH_UP",
    "RANDOM",
    "SPLIT_HORIZONTAL_IN",
    "SPLIT_HORIZONTAL_OUT",
    "SPLIT_VERTICAL_IN",
    "SPLIT_VERTICAL_OUT",
    "COVER_LEFT",
    "COVER_RIGHT",
    "TRANSITION_TYPES",
    "WIPE_DOWN",
    "WIPE_LEFT",
    "WIPE_RIGHT",
    "WIPE_UP",
    # Animations
    "ALL_ANIMATION_TYPES",
    "ANIMATION_TYPES",
    "APPEAR",
    "ASCEND",
    "BLINDS_IN",
    "BLINDS_OUT",
    "BOUNCE",
    "BOUNCE_OUT",
    "BOX_IN",
    "BOX_OUT",
    "BRUSH_ON_COLOR",
    "BRUSH_ON_UNDERLINE",
    "CHECKERBOARD_IN",
    "CHECKERBOARD_OUT",
    "COLOR_CHANGE",
    "DARKEN",
    "DESATURATE",
    "DESCEND",
    "DIAGONAL_IN",
    "DIAGONAL_OUT",
    "DISAPPEAR",
    "EMPHASIS_TYPES",
    "ENTRANCE_TYPES",
    "EXIT_TYPES",
    "FADE_IN",
    "FADE_OUT",
    "FILL_COLOR",
    "FLOAT_DOWN",
    "FLOAT_UP",
    "FLY_IN",
    "FLY_OUT",
    "FONT_COLOR",
    "GROW_SHRINK",
    "GROW_TURN",
    "LIGHTEN",
    "MOTION_PATH",
    "OBJECT_COLOR",
    "PULSE",
    "RANDOM_BARS_IN",
    "RANDOM_BARS_OUT",
    "SHRINK_TURN",
    "SPIN",
    "SPIN_IN",
    "SPLIT_IN",
    "SPLIT_OUT",
    "STRETCH_IN",
    "SWIVEL",
    "SWIVEL_OUT",
    "TEETER",
    "TRANSPARENCY",
    "WAVE",
    "WHEEL_IN",
    "WIPE_IN",
    "WIPE_OUT",
    "ZOOM",
    "ZOOM_OUT",
    "apply_animation",
    "apply_emphasis_animation",
    "apply_entrance_animation",
    "apply_exit_animation",
    "apply_motion_path",
    "list_animations",
    "remove_animations",
    # Watermark
    "add_image_watermark",
    "add_text_watermark",
    "list_watermarks",
    "remove_watermark",
    # Sections
    "SectionInfo",
    "add_section",
    "collapse_section",
    "list_sections",
    "move_section",
    "remove_section",
    "rename_section",
    # Slide Master
    "LayoutInfo",
    "MasterInfo",
    "add_placeholder_to_layout",
    "analyze_layout",
    "clone_layout",
    "delete_layout",
    "get_layout_by_name",
    "list_layouts",
    "list_placeholders",
    "list_slide_masters",
    "remove_placeholder_from_layout",
    "rename_layout",
    "set_layout_background",
    "set_master_background",
    # Image Optimize
    "CompressionLevel",
    "compress_images",
    "convert_image_format",
    "get_image_stats",
    "remove_unused_media",
    # Comments
    "add_comment",
    "append_speaker_notes",
    "delete_comment",
    "export_speaker_notes",
    "get_speaker_notes",
    "list_comments",
    "remove_speaker_notes",
    "reply_to_comment",
    "resolve_comment",
    "set_speaker_notes",
    # Diff
    "Change",
    "ChangeKind",
    "PresentationDiff",
    "diff_SlideDiff",
    "diff_presentations",
    "diff_presentations_visual",
    "diff_slides",
    "diff_text",
    "format_diff",
    "has_changes",
    # Export
    "export_thumbnails",
    "export_to_html",
    "export_to_images",
    "export_to_pdf",
    "export_to_text",
    # HTML Import
    "detect_html_slides",
    "html_to_content_spec",
    "import_from_html",
    # SmartArt
    "detect_smartart",
    "extract_smartart_text",
    "list_smartart_layouts",
    "populate_smartart_text",
    "preserve_smartart",
    "smartart_layout_info",
    # VBA
    "attach_macro_to_shape",
    "detach_macro_from_shape",
    "extract_vba_project",
    "has_vba_project",
    "inject_vba_project",
    "list_macro_names",
    "preserve_vba_project",
    # Table Styles
    "TABLE_STYLE_IDS",
    "add_table_column",
    "add_table_row",
    "apply_table_style",
    "merge_cells",
    "set_cell_border",
    "set_cell_fill",
    "set_cell_margins",
    "set_cell_vertical_alignment",
    "set_table_banding",
    "set_table_direction",
    "unmerge_cells",
    # HTML Import (duplicate entries removed above)
    # --- v4.0: Effects ---
    "BevelPreset",
    "EFFECT_PRESETS",
    "EffectInfo",
    "LightingPreset",
    "MaterialPreset",
    "apply_3d_format",
    "apply_effect_preset",
    "apply_glow",
    "apply_inner_shadow",
    "apply_perspective_shadow",
    "apply_reflection",
    "apply_shadow",
    "apply_soft_edges",
    "effects_pt_to_emu",
    "effects_inch_to_emu",
    "effects_cm_to_emu",
    "list_effects",
    "remove_3d_format",
    "remove_effect",
    "remove_effects",
    "remove_glow",
    "remove_reflection",
    "remove_shadow",
    "remove_soft_edges",
    # --- v4.0: Connectors ---
    "ARROW_DIAMOND",
    "ARROW_NONE",
    "ARROW_OVAL",
    "ARROW_OPEN",
    "ARROW_STEALTH",
    "ARROW_TRIANGLE",
    "ConnectorInfo",
    "DASH_DASH",
    "DASH_DASH_DOT",
    "DASH_DOT",
    "DASH_LG_DASH",
    "DASH_LG_DASH_DOT",
    "DASH_LG_DASH_DOT_DOT",
    "DASH_SOLID",
    "DASH_SYS_DASH",
    "DASH_SYS_DASH_DOT",
    "DASH_SYS_DOT",
    "LineInfo",
    "add_connector",
    "add_curved_connector",
    "add_curve",
    "add_elbow_connector",
    "add_freeform",
    "add_line",
    "delete_connector",
    "list_connectors",
    "reroute_connector",
    "set_arrow_style",
    "set_line_style",
    # --- v4.0: Protection ---
    "ProtectionInfo",
    "apply_write_protection",
    "decrypt_pptx",
    "encrypt_pptx",
    "get_protection_info",
    "is_encrypted",
    "is_marked_final",
    "mark_as_final",
    "remove_write_protection",
    "unmark_as_final",
    # --- v4.0: Accessibility ---
    "AccessibilityIssue",
    "AccessibilityReport",
    "accessibility_IssueKind",
    "accessibility_IssueSeverity",
    "add_title_to_slide",
    "audit_accessibility",
    "check_accessibility_contrast",
    "fix_accessibility",
    "get_alt_text",
    "remove_alt_text",
    "set_alt_text",
    "set_reading_order",
    # --- v4.0: Metadata ---
    "CustomProperty",
    "DocumentMetadata",
    "FontInfo",
    "delete_custom_property",
    "embed_font",
    "get_custom_property",
    "get_metadata",
    "list_custom_properties",
    "list_embedded_fonts",
    "remove_embedded_font",
    "set_custom_property",
    "set_metadata",
    # --- v4.0: Equations ---
    "OmmlBuilder",
    "add_equation_accent",
    "add_equation_bar",
    "add_equation_delimiter",
    "add_display_equation",
    "add_equation",
    "add_equation_border_box",
    "add_equation_fraction",
    "add_equation_function",
    "add_equation_group_character",
    "add_equation_limit_lower",
    "add_equation_limit_upper",
    "add_equation_matrix",
    "add_equation_nary",
    "add_equation_radical",
    "add_equation_subscript",
    "add_equation_sub_superscript",
    "add_equation_superscript",
    "add_equation_text_run",
    "latex_to_omml",
    "list_equations",
    "remove_equation",
    # --- v4.0: Multimedia ---
    "AudioInfo",
    "VideoInfo",
    "add_audio",
    "add_video",
    "extract_audio",
    "extract_video",
    "list_media",
    "remove_media",
    "set_audio_playback",
    "set_video_playback",
    # --- v4.0: Groups ---
    "GroupInfo",
    "add_to_group",
    "group_shapes",
    "list_group_children",
    "list_groups",
    "move_in_group",
    "remove_from_group",
    "ungroup_shapes",
    "ZoomInfo",
    "add_section_zoom",
    "add_slide_zoom",
    "add_summary_zoom",
    "list_zooms",
    "remove_zoom",
    # --- v5.0: Morph ---
    "MorphInfo",
    "has_morph_transition",
    "list_morph_transitions",
    "remove_morph_transition",
    "set_morph_options",
    "set_morph_transition",
    # --- v5.0: Extended Transitions ---
    "ADVANCED_TRANSITIONS",
    "AdvancedTransitionInfo",
    "has_advanced_transition",
    "list_advanced_transitions",
    "remove_advanced_transition",
    "set_advanced_transition",
    "set_flip_transition",
    "set_pan_transition",
    "set_ripple_transition",
    "set_wheel_transition",
    # --- v5.0: Batch ---
    "BatchResult",
    "BatchStats",
    "batch_apply",
    "batch_convert",
    "batch_export_images",
    "batch_inspect",
    "batch_merge",
    "batch_recolor",
    "batch_stats",
    "batch_watermark",
    # --- v5.0: SVG Import ---
    "PathData",
    "import_svg",
    "import_svg_as_image",
    "list_svg_shapes",
    "svg_to_drawingml",
    # --- v5.0: OCR ---
    "OcrEngine",
    "OcrResult",
    "auto_caption_presentation",
    "auto_caption_slide",
    "list_available_engines",
    "ocr_image",
    "ocr_presentation",
    "ocr_slide",
    # --- v5.0: Chart Edit ---
    "ChartInfo",
    "SeriesInfo",
    "add_chart_series",
    "edit_chart_data",
    "export_chart_data",
    "get_chart_info",
    "import_chart_data",
    "list_charts",
    "remove_chart_series",
    "rename_chart_series",
    "set_axis_number_format",
    "set_axis_range",
    "set_axis_title",
    "set_chart_colors",
    "set_chart_style",
    "set_chart_type",
    "set_data_labels",
    "set_legend",
    "toggle_gridlines",
    # --- v5.0: Color ---
    "ColorInfo",
    "GradientInfo",
    "GradientStop",
    "analogous_colors",
    "apply_gradient",
    "blend_colors",
    "cmyk_to_rgb",
    "complementary_colors",
    "contrast_color",
    "darken",
    "extract_palette",
    "hex_to_rgb",
    "hsl_to_rgb",
    "hsv_to_rgb",
    "lighten",
    "list_gradients",
    "monochromatic_colors",
    "recolor_presentation",
    "remove_gradient",
    "resolve_theme_color",
    "rgb_to_cmyk",
    "rgb_to_hex",
    "rgb_to_hsl",
    "rgb_to_hsv",
    "split_complementary_colors",
    "swap_colors",
    "tetradic_colors",
    "triadic_colors",
    # --- v5.0: Layout Sync ---
    "LayoutTemplate",
    "align_shapes",
    "apply_layout_template",
    "bring_to_front",
    "center_on_slide",
    "copy_layout",
    "create_layout_template",
    "distribute_shapes",
    "list_layout_templates",
    "match_position",
    "match_size",
    "move_down",
    "move_up",
    "send_to_back",
    "set_z_order",
    "snap_to_grid",
    # --- v5.1: Markdown Export ---
    "MarkdownOptions",
    "export_to_markdown",
    "extract_markdown_content",
    "slide_to_markdown",
    # --- v5.1: Video Export ---
    "VideoExportOptions",
    "video_VideoInfo",
    "check_ffmpeg",
    "export_to_gif",
    "export_to_video",
    "extract_audio_track",
    # --- v5.1: SVG Export ---
    "export_slide_to_svg",
    "export_to_svg",
    "shape_to_svg",
]
