"""Round-trip project manifests and backups for PPTX files generated by this skill."""

from __future__ import annotations

import copy
import json
import os
import shutil
import tempfile
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from xml.etree import ElementTree as ET


CUSTOM_NS = "http://schemas.openxmlformats.org/officeDocument/2006/custom-properties"
VT_NS = "http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes"
REL_NS = "http://schemas.openxmlformats.org/package/2006/relationships"
CT_NS = "http://schemas.openxmlformats.org/package/2006/content-types"
CUSTOM_XML_REL_TYPE = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/customXml"
MANIFEST_PART = "customXml/pptxSkillManifest.xml"
MANIFEST_NS = "urn:openai:pptx-skill:manifest:v2"

ET.register_namespace("", CUSTOM_NS)
ET.register_namespace("vt", VT_NS)


def _sidecar_path(pptx_path: str | Path) -> Path:
    path = Path(pptx_path)
    return path.with_suffix(".manifest.json")


def _backup_path(pptx_path: str | Path) -> Path:
    path = Path(pptx_path)
    return path.with_name(f"{path.stem}.bak{path.suffix}")


def create_backup(pptx_path: str | Path) -> Path:
    source = Path(pptx_path).resolve()
    if not source.exists():
        raise FileNotFoundError(source)
    backup = _backup_path(source)
    shutil.copy2(source, backup)
    sidecar = _sidecar_path(source)
    if sidecar.exists():
        shutil.copy2(sidecar, _sidecar_path(backup))
    return backup


def restore_backup(pptx_path: str | Path) -> bool:
    target = Path(pptx_path).resolve()
    backup = _backup_path(target)
    if not backup.exists():
        return False
    shutil.copy2(backup, target)
    backup_sidecar = _sidecar_path(backup)
    if backup_sidecar.exists():
        shutil.copy2(backup_sidecar, _sidecar_path(target))
    return True


def _manifest_xml(manifest_json: str) -> bytes:
    root = ET.Element(f"{{{MANIFEST_NS}}}manifest", {"version": "2"})
    payload = ET.SubElement(root, f"{{{MANIFEST_NS}}}json")
    payload.text = manifest_json
    return ET.tostring(root, encoding="utf-8", xml_declaration=True)


def _presentation_rels_xml(existing: bytes) -> bytes:
    root = ET.fromstring(existing)
    relationship_tag = f"{{{REL_NS}}}Relationship"
    target_name = "../customXml/pptxSkillManifest.xml"
    if not any(
        rel.get("Type") == CUSTOM_XML_REL_TYPE and rel.get("Target") == target_name
        for rel in root.findall(relationship_tag)
    ):
        used = {rel.get("Id") for rel in root.findall(relationship_tag)}
        number = 1
        while f"rId{number}" in used:
            number += 1
        ET.SubElement(root, relationship_tag, {
            "Id": f"rId{number}",
            "Type": CUSTOM_XML_REL_TYPE,
            "Target": target_name,
        })
    return ET.tostring(root, encoding="utf-8", xml_declaration=True)


def _embed_manifest(pptx_path: Path, project: dict) -> None:
    manifest_json = json.dumps(project, ensure_ascii=False, separators=(",", ":"))
    with zipfile.ZipFile(pptx_path, "r") as source:
        members = {item.filename: source.read(item.filename) for item in source.infolist()}
        infos = {item.filename: item for item in source.infolist()}
    members[MANIFEST_PART] = _manifest_xml(manifest_json)
    presentation_rels = "ppt/_rels/presentation.xml.rels"
    members[presentation_rels] = _presentation_rels_xml(members[presentation_rels])

    temp_fd, temp_name = tempfile.mkstemp(suffix=".pptx", dir=str(pptx_path.parent))
    os.close(temp_fd)
    try:
        with zipfile.ZipFile(temp_name, "w", compression=zipfile.ZIP_DEFLATED) as target:
            for name, data in members.items():
                if name in infos:
                    target.writestr(infos[name], data)
                else:
                    target.writestr(name, data)
        os.replace(temp_name, pptx_path)
    finally:
        if os.path.exists(temp_name):
            os.unlink(temp_name)


def save_project_manifest(pptx_path: str | Path, project: dict) -> None:
    """Embed the manifest and write a readable sidecar fallback."""
    path = Path(pptx_path).resolve()
    payload = copy.deepcopy(project)
    payload.setdefault("skill_version", 2)
    payload.setdefault("generated_at", datetime.now(timezone.utc).isoformat())
    sidecar = _sidecar_path(path)
    with sidecar.open("w", encoding="utf-8", newline="\n") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2)
        handle.write("\n")
    try:
        _embed_manifest(path, payload)
    except Exception as exc:
        warnings = payload.setdefault("warnings", [])
        if not isinstance(warnings, list):
            warnings = []
            payload["warnings"] = warnings
        warnings.append(f"Embedded manifest failed: {exc}")
        with sidecar.open("w", encoding="utf-8", newline="\n") as handle:
            json.dump(payload, handle, ensure_ascii=False, indent=2)
            handle.write("\n")


def _read_embedded_manifest(pptx_path: Path) -> dict | None:
    try:
        with zipfile.ZipFile(pptx_path, "r") as package:
            data = package.read(MANIFEST_PART)
        root = ET.fromstring(data)
        value = root.find(f"{{{MANIFEST_NS}}}json")
        if value is not None and value.text:
            return json.loads(value.text)
    except (KeyError, ValueError, ET.ParseError, zipfile.BadZipFile):
        return None
    return None


def _relocate_images(project: dict, pptx_path: Path) -> None:
    image_dir = Path(project.get("image_dir") or pptx_path.parent)
    candidates = [image_dir, pptx_path.parent, pptx_path.parent / image_dir.name]
    for section in project.get("sections", []) or []:
        relocated = []
        for image in section.get("images", []) or []:
            original = Path(image)
            if original.exists():
                relocated.append(str(original.resolve()))
                continue
            found = next((base / original.name for base in candidates if (base / original.name).exists()), None)
            relocated.append(str(found.resolve()) if found else "")
        section["images"] = [item for item in relocated if item]


def load_project(pptx_path: str | Path) -> dict | None:
    path = Path(pptx_path).resolve()
    if not path.exists():
        raise FileNotFoundError(path)
    project = _read_embedded_manifest(path)
    if project is None:
        sidecar = _sidecar_path(path)
        if not sidecar.exists():
            return None
        try:
            with sidecar.open("r", encoding="utf-8") as handle:
                project = json.load(handle)
        except (json.JSONDecodeError, UnicodeDecodeError) as exc:
            raise ValueError(f"Invalid manifest sidecar: {sidecar}") from exc
        if not isinstance(project, dict):
            raise TypeError(f"Manifest sidecar must contain an object: {sidecar}")
    _relocate_images(project, path)
    project["source_pptx"] = str(path)
    return project


def regenerate(project: dict, output_path: str | Path | None = None) -> str:
    from pptx_helper import auto_generate_ppt

    payload = copy.deepcopy(project)
    source = Path(payload.get("source_pptx", "")) if payload.get("source_pptx") else None
    target = Path(output_path).resolve() if output_path else source
    if target is None:
        raise ValueError("output_path is required when project has no source_pptx")
    if target.exists() and source and target == source:
        create_backup(target)

    layouts = payload.get("layouts", [])
    sections = payload.get("sections", [])
    content_layouts = [
        layout for layout in layouts
        if layout not in {"cover", "toc", "end"}
    ]
    for section, layout in zip(sections, content_layouts):
        section.setdefault("layout", layout)
    return auto_generate_ppt(
        title=payload.get("title", ""),
        subtitle=payload.get("subtitle", ""),
        sections=sections,
        output_path=str(target),
        theme_key=payload.get("theme_key"),
        image_dir=payload.get("image_dir", str(target.parent / "ppt_images")),
        auto_search_images=payload.get("auto_search_images", False),
        lang=payload.get("lang", "zh"),
        template_key=payload.get("template_key"),
        template_profile=payload.get("template_profile"),
    )


def edit_section(
    pptx_path: str | Path,
    index: int,
    changes: dict,
    output_path: str | Path | None = None,
) -> str:
    project = load_project(pptx_path)
    if project is None:
        raise ValueError("This PPTX has no skill manifest; use ppt_edit.py for direct edits")
    sections = project.get("sections", [])
    resolved = index - 1 if index > 0 else 0
    if not 0 <= resolved < len(sections):
        raise IndexError(f"Section index out of range: {index}")
    sections[resolved].update(changes)
    return regenerate(project, output_path)
